// Scalp-engine audit: replays the production engine over 36 months of BTCUSDT and evaluates every
// alert type + the executed paper trades, per chronological split. OOS (last 20%) is WITHHELD unless
// --oos is passed, so classification decisions are taken on train+validation only.
//   npx tsx scripts/audit/runScalpAudit.ts [--oos]
import { mkdirSync, writeFileSync } from 'node:fs'
import {
  Horizon, ROUND_TRIP_COST, TRAIN_END, VAL_END, DATA_START, DATA_END, bootstrapMeanCI, firstPassageTable, loadDataset, mean, median, num, pct,
  quantile, realizedVol, splitOf, summarize, toBars, type SignalEvent,
} from './lib'
import { replayScalp, type ReplayEvent, type ReplayTrade } from './scalpReplay'
import { DEFAULT_STRATEGY_CONFIG, type StrategyConfig } from '../../src/config/strategyConfig'

const INCLUDE_OOS = process.argv.includes('--oos')
const ds = loadDataset()
const bars = toBars(ds.spot_15m)
const HORIZONS: Horizon[] = [
  { label: '15m', bars: 1 }, { label: '30m', bars: 2 }, { label: '1h', bars: 4 },
  { label: '4h', bars: 16 }, { label: '12h', bars: 48 }, { label: '24h', bars: 96 },
]
const RANGES: Record<string, [number, number]> = {
  train: [DATA_START, TRAIN_END],
  val: [TRAIN_END, VAL_END],
  'train+val': [DATA_START, VAL_END],
  ...(INCLUDE_OOS ? { oos: [VAL_END, DATA_END] as [number, number] } : {}),
}

const out: Record<string, unknown> = { includeOos: INCLUDE_OOS, roundTripCost: ROUND_TRIP_COST }
const md: string[] = []
const log = (s = '') => { console.log(s); md.push(s) }

const base = replayScalp(ds.spot_15m, ds.spot_1h, ds.spot_4h)
out.regimeShare = base.regimeShare
log(`# Scalp engine replay — generated by scripts/audit/runScalpAudit.ts (OOS ${INCLUDE_OOS ? 'INCLUDED' : 'WITHHELD'})`)
log(`Bars evaluated: ${base.barsEvaluated}; 4h regime share: bullish ${pct(base.regimeShare.bullish, 1)}, bearish ${pct(base.regimeShare.bearish, 1)}, neutral ${pct(base.regimeShare.neutral, 1)}`)

const toEvents = (evs: ReplayEvent[]): SignalEvent[] => evs.filter((e) => e.dir !== 0).map((e) => ({ i: e.i, dir: e.dir as 1 | -1, t: e.t }))

// ---- per-alert-type forward statistics --------------------------------------------------------
for (const type of ['SETUP_DETECTED', 'ENTRY_CONFIRMED', 'SETUP_INVALIDATED'] as const) {
  const events = toEvents(base.events.filter((e) => e.type === type))
  log(`\n## ${type}  (direction-adjusted to the setup direction; returns are from signal-bar close; NET = minus ${pct(ROUND_TRIP_COST, 2)} round-trip)`)
  const perSplit: Record<string, unknown> = {}
  for (const [name, [from, to]] of Object.entries(RANGES)) {
    const stats = summarize(bars, events, HORIZONS, from, to)
    perSplit[name] = stats
    log(`\n### ${type} — ${name}`)
    log('| horizon | n | n_indep | mean gross | median gross | mean net | mean net (1-bar delay) | 95% CI net | %>0 net | baseline | excess net | 95% CI excess | mean MFE | mean MAE |')
    log('|---|---|---|---|---|---|---|---|---|---|---|---|---|---|')
    for (const s of stats) {
      log(`| ${s.horizon} | ${s.n} | ${s.nIndep} | ${pct(s.meanGross)} | ${pct(s.medianGross)} | ${pct(s.meanNet)} | ${pct(s.meanNetDelayed)} | [${pct(s.ciNet[0])}, ${pct(s.ciNet[1])}] | ${pct(s.pctPositiveNet, 1)} | ${pct(s.baselineMeanGross)} | ${pct(s.excessNet)} | [${pct(s.ciExcessNet[0])}, ${pct(s.ciExcessNet[1])}] | ${pct(s.meanMfe)} | ${pct(s.meanMae)} |`)
    }
  }
  out[type] = perSplit
  // first-passage on the pooled decision range (train+val) [+ oos if allowed]
  for (const name of Object.keys(RANGES).filter((n) => n === 'train+val' || n === 'oos')) {
    const [from, to] = RANGES[name]
    const fp = [16, 96].map((H) => ({ H, rows: firstPassageTable(bars, events, H, [0.0025, 0.005, 0.01, 0.02], from, to) }))
    ;(out[`${type}_firstPassage_${name}`] as unknown) = fp
    log(`\n### ${type} — first passage (target X in favour BEFORE X against; ${name})`)
    log('| horizon | X | n | P(target first) | P(adverse first) | P(neither) |')
    log('|---|---|---|---|---|---|')
    for (const { H, rows } of fp) for (const r of rows) log(`| ${H === 16 ? '4h' : '24h'} | ${pct(r.X, 2)} | ${r.n} | ${pct(r.pTarget, 1)} | ${pct(r.pAdverse, 1)} | ${pct(r.pNeither, 1)} |`)
  }
}

// ---- executed paper trades (ENTRY_CONFIRMED lifecycle) -----------------------------------------
function tradeStats(ts: ReplayTrade[]) {
  const net = ts.map((t) => t.pnlRNet)
  const gross = ts.map((t) => t.pnlRGross)
  const wins = net.filter((x) => x > 0)
  const gw = wins.reduce((a, b) => a + b, 0)
  const gl = Math.abs(net.filter((x) => x <= 0).reduce((a, b) => a + b, 0))
  return {
    n: ts.length,
    winRate: ts.length ? wins.length / ts.length : NaN,
    meanNetR: mean(net), medianNetR: median(net), meanGrossR: mean(gross),
    ciNetR: bootstrapMeanCI(net),
    profitFactor: gl > 0 ? gw / gl : gw > 0 ? Infinity : 0,
    totalNetR: net.reduce((a, b) => a + b, 0),
    best: net.length ? Math.max(...net) : NaN, worst: net.length ? Math.min(...net) : NaN,
    stops: ts.filter((t) => t.result === 'SL').length, tp1: ts.filter((t) => t.result === 'TP1').length, tp2: ts.filter((t) => t.result === 'TP2').length,
    avgBarsHeld: mean(ts.map((t) => t.exitI - t.entryI)),
  }
}
const inRange = (t: ReplayTrade, [f, to]: [number, number]) => t.entryT >= f && t.entryT < to
log('\n## Executed paper trades (engine\'s own SL/TP; fees+spread+slippage already netted)')
log('| split | n | win rate | mean net R | 95% CI mean net R | mean gross R | profit factor | total net R | stops | TP1 | TP2 | avg bars held |')
log('|---|---|---|---|---|---|---|---|---|---|---|---|')
const tradesBySplit: Record<string, unknown> = {}
for (const [name, r] of Object.entries(RANGES)) {
  const s = tradeStats(base.trades.filter((t) => inRange(t, r)))
  tradesBySplit[name] = s
  log(`| ${name} | ${s.n} | ${pct(s.winRate, 1)} | ${num(s.meanNetR)} | [${num(s.ciNetR[0])}, ${num(s.ciNetR[1])}] | ${num(s.meanGrossR)} | ${num(s.profitFactor, 2)} | ${num(s.totalNetR, 2)} | ${s.stops} | ${s.tp1} | ${s.tp2} | ${num(s.avgBarsHeld, 1)} |`)
}
out.trades = tradesBySplit

// by direction / regime / vol tercile (vol thresholds fitted on TRAIN only) / confidence bucket — decision range only
const volTrain = bars.map((_, i) => (bars[i].ct < TRAIN_END ? realizedVol(bars, i) : NaN)).filter(Number.isFinite)
const v1 = quantile(volTrain, 1 / 3)
const v2 = quantile(volTrain, 2 / 3)
const volBucket = (i: number) => { const v = realizedVol(bars, i); return v < v1 ? 'low-vol' : v < v2 ? 'mid-vol' : 'high-vol' }
const decisionRange: [number, number] = INCLUDE_OOS ? [DATA_START, DATA_END] : [DATA_START, VAL_END]
const dt = base.trades.filter((t) => inRange(t, decisionRange))
log(`\n### Trade breakdown (${INCLUDE_OOS ? 'ALL splits' : 'train+val'}; vol terciles fitted on train: ${pct(v1, 3)} / ${pct(v2, 3)} per-15m stdev)`)
log('| slice | n | win rate | mean net R | total net R |')
log('|---|---|---|---|---|')
const slices: Record<string, (t: ReplayTrade) => boolean> = {
  long: (t) => t.dir === 1, short: (t) => t.dir === -1,
  'low-vol': (t) => volBucket(t.entryI) === 'low-vol', 'mid-vol': (t) => volBucket(t.entryI) === 'mid-vol', 'high-vol': (t) => volBucket(t.entryI) === 'high-vol',
  'conf<70': (t) => t.confidence < 70, 'conf 70-79': (t) => t.confidence >= 70 && t.confidence < 80, 'conf>=80': (t) => t.confidence >= 80,
}
const sliceOut: Record<string, unknown> = {}
for (const [k, f] of Object.entries(slices)) {
  const s = tradeStats(dt.filter(f))
  sliceOut[k] = s
  log(`| ${k} | ${s.n} | ${pct(s.winRate, 1)} | ${num(s.meanNetR)} | ${num(s.totalNetR, 2)} |`)
}
out.tradeSlices = sliceOut

// EXIT_SUGGESTED usefulness: net R if closed at suggestion vs. what the trade actually realised
const sugg = dt.filter((t) => t.pnlRAtExitSuggestion !== undefined)
log(`\n### EXIT_SUGGESTED (${sugg.length} of ${dt.length} trades got a suggestion)`)
if (sugg.length) {
  const realised = sugg.map((t) => t.pnlRNet)
  const atSugg = sugg.map((t) => t.pnlRAtExitSuggestion as number)
  const better = sugg.filter((t) => (t.pnlRAtExitSuggestion as number) > t.pnlRNet).length
  log(`mean net R if exited at suggestion: ${num(mean(atSugg))}; mean net R as realised by engine SL/TP: ${num(mean(realised))}; suggestion better than realised in ${better}/${sugg.length}`)
  out.exitSuggested = { n: sugg.length, meanAtSuggestion: mean(atSugg), meanRealised: mean(realised), better }
}

// ---- parameter sensitivity (±10%) on the decision range ---------------------------------------
log('\n## Sensitivity (±10% on each numeric threshold; decision range only; one parameter at a time)')
log('| parameter | value | trades | mean net R | total net R | profit factor |')
log('|---|---|---|---|---|---|')
const sens: { key: keyof StrategyConfig; }[] = [
  { key: 'minSignalConfidence' }, { key: 'minRiskReward' }, { key: 'volumeConfirmMult' }, { key: 'maxStopAtr' }, { key: 'zoneClusterPct' }, { key: 'atrStopBufferMult' },
]
const sensOut: unknown[] = []
for (const { key } of sens) {
  const v0 = DEFAULT_STRATEGY_CONFIG[key] as number
  for (const mult of [0.9, 1, 1.1]) {
    const cfg = { ...DEFAULT_STRATEGY_CONFIG, [key]: v0 * mult } as StrategyConfig
    const r = replayScalp(ds.spot_15m, ds.spot_1h, ds.spot_4h, cfg)
    const s = tradeStats(r.trades.filter((t) => inRange(t, decisionRange)))
    sensOut.push({ key, value: v0 * mult, ...s })
    log(`| ${String(key)} | ${(v0 * mult).toFixed(4)}${mult === 1 ? ' (default)' : ''} | ${s.n} | ${num(s.meanNetR)} | ${num(s.totalNetR, 2)} | ${num(s.profitFactor, 2)} |`)
  }
}
out.sensitivity = sensOut

mkdirSync('docs/audit/data', { recursive: true })
const tag = INCLUDE_OOS ? 'with_oos' : 'decision_range'
writeFileSync(`docs/audit/data/scalp_${tag}.json`, JSON.stringify(out, null, 1))
writeFileSync(`docs/audit/data/scalp_${tag}.md`, md.join('\n') + '\n')
console.log(`\nwritten docs/audit/data/scalp_${tag}.{json,md}`)
